apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-book-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-book-client
  template:
    metadata:
      labels:
        app: recipe-book-client
    spec:
      containers:
      - name: recipe-book-client
        image: ghcr.io/steven-mercatante/recipe-book-client:latest # {"$imagepolicy": "flux-system:recipe-book-client"}
#        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: recipe-book-client-config
          - secretRef:
              name: recipe-book-client-secret
#        securityContext:
          # prevent the container from running as root
#          runAsNonRoot: true
        ports:
        - containerPort: 3000
#        resources:
#          requests:
#            memory: "10Mi"
#            cpu: "100m"
#          limits:
#            memory: "20Mi"
#            cpu: "250m"
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
