apiVersion: v1
kind: Service
metadata:
  name: recipe-book-client
  labels:
    app: recipe-book-client
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: recipe-book-client
  type: LoadBalancer