apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-book-api
  template:
    metadata:
      labels:
        app: recipe-book-api
    spec:
      containers:
      - name: recipe-book-api
        image: ghcr.io/steven-mercatante/recipe-book-api:main
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: recipe-book-api-config
          - secretRef:
              name: recipe-book-api-secret
        ports:
        - containerPort: 8000
#        livenessProbe:
#          httpGet:
#            path: /api
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
