apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-book-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-book-api
  template:
    metadata:
      labels:
        app: recipe-book-api
    spec:
      containers:
      - name: recipe-book-api
        image: ghcr.io/steven-mercatante/recipe-book-api:main
        ports:
        - containerPort: 8000
#        resources:
#          requests:
#            memory: "10Mi"
#            cpu: "100m"
#          limits:
#            memory: "20Mi"
#            cpu: "250m"
#        livenessProbe:
#          httpGet:
#            path: /api
#            port: 8000
#          initialDelaySeconds: 3
#          periodSeconds: 3
